# Generated by Django 4.2.7 on 2026-05-30 13:22

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('cor', models.CharField(default='#7c6af7', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/logos/')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído')], default='ativo', max_length=10)),
                ('invite_code', models.CharField(db_index=True, default=apps.projects.models._generate_invite_code, max_length=8, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.IntegerField(default=0)),
                ('is_done_column', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.project')),
            ],
            options={
                'verbose_name': 'Coluna',
                'verbose_name_plural': 'Colunas',
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro do Projeto',
                'verbose_name_plural': 'Membros do Projeto',
                'ordering': ['-criado_em'],
                'unique_together': {('projeto', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['criado_por', '-criado_em'], name='projects_pr_criado__c102ba_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-criado_em'], name='projects_pr_status_21cd99_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deletado_em'], name='projects_pr_deletad_1ad6de_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['projeto', 'posicao'], name='projects_co_projeto_75d1d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('nome', 'criado_por')},
        ),
    ]
