# Generated by Django 4.2.7 on 2026-03-18 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='backlog', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('atribuido_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Histórico de Task',
                'verbose_name_plural': 'Histórico de Tasks',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['task', '-changed_at'], name='tasks_taskh_task_id_734326_idx'), models.Index(fields=['changed_by', '-changed_at'], name='tasks_taskh_changed_c83dfc_idx'), models.Index(fields=['field_name', '-changed_at'], name='tasks_taskh_field_n_791f59_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-criado_em'], name='tasks_task_status_5afc77_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['criado_por', '-criado_em'], name='tasks_task_criado__801722_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['atribuido_para', '-criado_em'], name='tasks_task_atribui_723934_idx'),
        ),
    ]
