# Generated by Django 4.2.7 on 2026-03-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deletado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deletado_em'], name='tasks_task_deletad_07da9f_idx'),
        ),
    ]
